Repository magento/magento-cloud, pull requests merged in 2018-02, with the labels that each got.

#98 MAGECLOUD-1743: The directory 'm2-hotfixes' should not be ignored by Git
  .gitignore
Labels: 2.2.0

#99 MAGECLOUD-1743: The directory 'm2-hotfixes' should not be ignored by Git
  .gitignore
Labels: 2.2.1

#100 MAGECLOUD-1743: The directory 'm2-hotfixes' should not be ignored by Git
  .gitignore
Labels: 2.2.2

#93 MAGECLOUD-1720: Upgrade PHP version to 7.1 in Cloud Templates
  .magento.app.yaml
  composer.lock
Labels: master

#94 MAGECLOUD-1720: Upgrade PHP version to 7.1 in Cloud Templates
  .magento.app.yaml
  composer.lock
Labels: 2.2.0

#95 MAGECLOUD-1720: Upgrade PHP version to 7.1 in Cloud Templates
  .magento.app.yaml
  composer.lock
Labels: 2.2.1

#96 MAGECLOUD-1720: Upgrade PHP version to 7.1 in Cloud Templates
  .magento.app.yaml
  composer.lock
Labels: 2.2.2

#103 MAGECLOUD-1765: Prepare Templates for Migration to ECE-Tools 2.2.x
  composer.json
  composer.lock
Labels: 2.2.2

#102 MAGECLOUD-1765: Prepare Templates for Migration to ECE-Tools 2.2.x
  composer.json
  composer.lock
Labels: 2.2.1

#101 MAGECLOUD-1765: Prepare Templates for Migration to ECE-Tools 2.2.x
  composer.json
  composer.lock
Labels: 2.2.0

#113 MAGECLOUD-1765: Prepare Templates for Migration to ECE-Tools 2.2.x
  composer.json
  composer.lock
Labels: 2.2.2, master

#105 MAGECLOUD-1758: Prepare Templates for Migration to ECE-Tools
  .magento.app.yaml
  composer.json
  composer.lock
Labels: 2.1.4

#107 MAGECLOUD-1758: Prepare Templates for Migration to ECE-Tools
  .magento.app.yaml
  composer.json
  composer.lock
Labels: 2.1.6

#109 MAGECLOUD-1758: Prepare Templates for Migration to ECE-Tools
  .magento.app.yaml
  composer.json
  composer.lock
Labels: 2.1.8

#111 MAGECLOUD-1758: Prepare Templates for Migration to ECE-Tools
  .magento.app.yaml
  composer.json
  composer.lock
Labels: 2.1.10

#112 MAGECLOUD-1758: Prepare Templates for Migration to ECE-Tools
  .magento.app.yaml
  composer.json
  composer.lock
Labels: 2.1.11

#106 MAGECLOUD-1758: Prepare Templates for Migration to ECE-Tools
  .magento.app.yaml
  composer.json
  composer.lock
Labels: 2.1.5

#108 MAGECLOUD-1758: Prepare Templates for Migration to ECE-Tools
  .magento.app.yaml
  composer.json
  composer.lock
Labels: 2.1.7

#110 MAGECLOUD-1758: Prepare Templates for Migration to ECE-Tools
  .magento.app.yaml
  composer.json
  composer.lock
Labels: 2.1.9

#131 MAGECLOUD-1774: Update to Magento 2.2.3
  composer.json
  composer.lock
Labels: 2.2.3
