Repository magento/magento-cloud, pull requests merged in 2018-06, with the labels that each got.

#217 MAGETWO-91944: Transfer one of existing PAT scenarios to BlackFire
  .blackfire.yml
  .gitignore
  scenario.bkf
Labels: master

#215 MAGECLOUD-2108: Remove .magento.env.yaml.sample from all templates af…
  .magento.env.yaml
Labels: 2.2.4, onhold

#214 MAGECLOUD-2108: Remove .magento.env.yaml.sample from all templates af…
  .magento.env.yaml
Labels: 2.2.3, onhold

#213 MAGECLOUD-2108: Remove .magento.env.yaml.sample from all templates af…
  .magento.env.yaml
Labels: 2.2.2, onhold

#212 MAGECLOUD-2108: Remove .magento.env.yaml.sample from all templates af…
  .magento.env.yaml
Labels: 2.2.1, onhold

#211 MAGECLOUD-2108: Remove .magento.env.yaml.sample from all templates af…
  .magento.env.yaml
Labels: 2.2.0, onhold

#210 MAGECLOUD-2108: Remove .magento.env.yaml.sample from all templates af…
  .magento.env.yaml
Labels: 2.1.13, onhold

#209 MAGECLOUD-2108: Remove .magento.env.yaml.sample from all templates af…
  .magento.env.yaml
Labels: 2.1.12, onhold

#216 MAGECLOUD-2108: Remove .magento.env.yaml.sample from all templates af…
  .magento.env.yaml
Labels: master, onhold

#207 MAGECLOUD-2108: Remove .magento.env.yaml.sample from all templates af…
  .magento.env.yaml
Labels: 2.1.10, onhold

#205 MAGECLOUD-2108: Remove .magento.env.yaml.sample from all templates af…
  .magento.env.yaml
Labels: 2.1.8, onhold

#204 MAGECLOUD-2108: Remove .magento.env.yaml.sample from all templates af…
  .magento.env.yaml
Labels: 2.1.7, onhold

#203 MAGECLOUD-2108: Remove .magento.env.yaml.sample from all templates af…
  .magento.env.yaml
Labels: 2.1.6, onhold

#202 MAGECLOUD-2108: Remove .magento.env.yaml.sample from all templates af…
  .magento.env.yaml
Labels: 2.1.5, onhold

#201 MAGECLOUD-2108: Remove .magento.env.yaml.sample from all templates af…
  .magento.env.yaml
Labels: 2.1.4, onhold

#219 MAGECLOUD-1999: Update magento-cloud Templates to Support Robots / Sitemap Generation Flows
  .magento.app.yaml
Labels: 2.2.4

#218 MAGECLOUD-1999: Update magento-cloud Templates to Support Robots / Sitemap Generation Flows
  .magento.app.yaml
Labels: 2.1.13

#149 MAGECLOUD-1999: Update magento-cloud Templates to Support Robots / Sitemap Generation Flows
  .magento.app.yaml
Labels: master

#139 MAGECLOUD-1999: Update magento-cloud Templates to Support Robots / Sitemap Generation Flows
  .magento.app.yaml
Labels: 2.1.7

#138 MAGECLOUD-1999: Update magento-cloud Templates to Support Robots / Sitemap Generation Flows
  .magento.app.yaml
Labels: 2.1.6

#137 MAGECLOUD-1999: Update magento-cloud Templates to Support Robots / Sitemap Generation Flows
  .magento.app.yaml
Labels: 2.1.5

#136 MAGECLOUD-1999: Update magento-cloud Templates to Support Robots / Sitemap Generation Flows
  .magento.app.yaml
Labels: 2.1.4

#148 MAGECLOUD-1999: Update magento-cloud Templates to Support Robots / Sitemap Generation Flows
  .magento.app.yaml
Labels: 2.2.3

#140 MAGECLOUD-1999: Update magento-cloud Templates to Support Robots / Sitemap Generation Flows
  .magento.app.yaml
Labels: 2.1.8

#147 MAGECLOUD-1999: Update magento-cloud Templates to Support Robots / Sitemap Generation Flows
  .magento.app.yaml
Labels: 2.2.2

#146 MAGECLOUD-1999: Update magento-cloud Templates to Support Robots / Sitemap Generation Flows
  .magento.app.yaml
Labels: 2.2.1

#145 MAGECLOUD-1999: Update magento-cloud Templates to Support Robots / Sitemap Generation Flows
  .magento.app.yaml
Labels: 2.2.0

#144 MAGECLOUD-1999: Update magento-cloud Templates to Support Robots / Sitemap Generation Flows
  .magento.app.yaml
Labels: 2.1.12

#143 MAGECLOUD-1999: Update magento-cloud Templates to Support Robots / Sitemap Generation Flows
  .magento.app.yaml
Labels: 2.1.11

#142 MAGECLOUD-1999: Update magento-cloud Templates to Support Robots / Sitemap Generation Flows
  .magento.app.yaml
Labels: 2.1.10

#141 MAGECLOUD-1999: Update magento-cloud Templates to Support Robots / Sitemap Generation Flows
  .magento.app.yaml
Labels: 2.1.9

#237 MAGECLOUD-2350: Problem with images after upgrade from 2.2.4 to 2.3
  .magento.app.yaml
Labels: 2.1.13, approved

#236 MAGECLOUD-2350: Problem with images after upgrade from 2.2.4 to 2.3
  .magento.app.yaml
Labels: 2.1.12, approved

#235 MAGECLOUD-2350: Problem with images after upgrade from 2.2.4 to 2.3
  .magento.app.yaml
Labels: 2.1.11, approved

#234 MAGECLOUD-2350: Problem with images after upgrade from 2.2.4 to 2.3
  .magento.app.yaml
Labels: 2.1.10, approved

#233 MAGECLOUD-2350: Problem with images after upgrade from 2.2.4 to 2.3
  .magento.app.yaml
Labels: 2.1.9, approved

#232 MAGECLOUD-2350: Problem with images after upgrade from 2.2.4 to 2.3
  .magento.app.yaml
Labels: 2.1.8, approved

#231 MAGECLOUD-2350: Problem with images after upgrade from 2.2.4 to 2.3
  .magento.app.yaml
Labels: 2.1.7, approved

#230 MAGECLOUD-2350: Problem with images after upgrade from 2.2.4 to 2.3
  .magento.app.yaml
Labels: 2.1.6, approved

#229 MAGECLOUD-2350: Problem with images after upgrade from 2.2.4 to 2.3
  .magento.app.yaml
Labels: 2.1.5, approved

#228 MAGECLOUD-2350: Problem with images after upgrade from 2.2.4 to 2.3
  .magento.app.yaml
Labels: 2.1.4, approved

#227 MAGECLOUD-2350: Problem with images after upgrade from 2.2.4 to 2.3
  .magento.app.yaml
Labels: 2.2.0, approved

#226 MAGECLOUD-2350: Problem with images after upgrade from 2.2.4 to 2.3
  .magento.app.yaml
Labels: 2.2.1, approved

#225 MAGECLOUD-2350: Problem with images after upgrade from 2.2.4 to 2.3
  .magento.app.yaml
Labels: 2.2.2, approved

#224 MAGECLOUD-2350: Problem with images after upgrade from 2.2.4 to 2.3
  .magento.app.yaml
Labels: 2.2.3, approved

#222 MAGECLOUD-2350: [Investigate] Problem with images after upgrade from 2.2.4 to 2.3
  .magento.app.yaml
Labels: 2.2.4, approved

#223 MAGECLOUD-2350: [Investigate] Problem with images after upgrade from 2.2.4 to 2.3
  .magento.app.yaml
Labels: approved, master
