Repository magento/magento-cloud, pull requests merged in 2019-01, with the labels that each got.

#333 MAGECLOUD-2789: [GitHub] Fix deprecated application endpoint in templates
  .magento/routes.yaml
Labels: 2.3.0

#332 MAGECLOUD-2789: [GitHub] Fix deprecated application endpoint in templates
  .magento/routes.yaml
Labels: 2.2.7

#331 MAGECLOUD-2789: [GitHub] Fix deprecated application endpoint in templates
  .magento/routes.yaml
Labels: 2.2.6

#330 MAGECLOUD-2789: [GitHub] Fix deprecated application endpoint in templates
  .magento/routes.yaml
Labels: 2.2.5

#329 MAGECLOUD-2789: [GitHub] Fix deprecated application endpoint in templates
  .magento/routes.yaml
Labels: 2.2.4

#328 MAGECLOUD-2789: [GitHub] Fix deprecated application endpoint in templates
  .magento/routes.yaml
Labels: 2.2.3

#327 MAGECLOUD-2789: [GitHub] Fix deprecated application endpoint in templates
  .magento/routes.yaml
Labels: 2.2.2

#326 MAGECLOUD-2789: [GitHub] Fix deprecated application endpoint in templates
  .magento/routes.yaml
Labels: 2.2.1

#325 MAGECLOUD-2789: [GitHub] Fix deprecated application endpoint in templates
  .magento/routes.yaml
Labels: 2.2.0

#324 MAGECLOUD-2789: [GitHub] Fix deprecated application endpoint in templates
  .magento/routes.yaml
Labels: 2.1.16

#323 MAGECLOUD-2789: [GitHub] Fix deprecated application endpoint in templates
  .magento/routes.yaml
Labels: 2.1.15

#322 MAGECLOUD-2789: [GitHub] Fix deprecated application endpoint in templates
  .magento/routes.yaml
Labels: 2.1.14

#321 MAGECLOUD-2789: [GitHub] Fix deprecated application endpoint in templates
  .magento/routes.yaml
Labels: 2.1.13

#320 MAGECLOUD-2789: [GitHub] Fix deprecated application endpoint in templates
  .magento/routes.yaml
Labels: 2.1.12

#319 MAGECLOUD-2789: [GitHub] Fix deprecated application endpoint in templates
  .magento/routes.yaml
Labels: 2.1.11

#318 MAGECLOUD-2789: [GitHub] Fix deprecated application endpoint in templates
  .magento/routes.yaml
Labels: 2.1.10

#317 MAGECLOUD-2789: [GitHub] Fix deprecated application endpoint in templates
  .magento/routes.yaml
Labels: 2.1.9

#316 MAGECLOUD-2789: [GitHub] Fix deprecated application endpoint in templates
  .magento/routes.yaml
Labels: 2.1.8

#295 Use the non-deprecated application endpoint
  .magento/routes.yaml
Labels: acknowledged, master

#315 MAGECLOUD-2789: [GitHub] Fix deprecated application endpoint in templates
  .magento/routes.yaml
Labels: 2.1.7

#314 MAGECLOUD-2789: [GitHub] Fix deprecated application endpoint in templates
  .magento/routes.yaml
Labels: 2.1.6

#313 MAGECLOUD-2789: [GitHub] Fix deprecated application endpoint in templates
  .magento/routes.yaml
Labels: 2.1.5

#312 MAGECLOUD-2789: [GitHub] Fix deprecated application endpoint in templates
  .magento/routes.yaml
Labels: 2.1.4

#299 MAGECLOUD-1802: Update readme
  README.md
Labels: approved, master
