Repository magento/magento-cloud, pull requests merged in 2020-08, with the labels that each got.

#484 MCLOUD-6822: Update magento cloud template to use ES 7.7 by default
  .magento/services.yaml
Labels: approved, master

#485 MCLOUD-6822: Update magento cloud template to use ES 7.7 by default
  .magento/services.yaml
Labels: 2.4.0, approved

#489 MCLOUD-2649: [opcache] Disable timestamps validation
  op-exclude.txt
  php.ini
Labels: master

#490 MCLOUD-2649: [opcache] Disable timestamps validation
  op-exclude.txt
  php.ini
Labels: 2.4.0

#509 MCLOUD-2649: [opcache] Disable timestamps validation
  op-exclude.txt
  php.ini
Labels: 2.1.18

#508 MCLOUD-2649: [opcache] Disable timestamps validation
  op-exclude.txt
  php.ini
Labels: 2.2.0

#507 MCLOUD-2649: [opcache] Disable timestamps validation
  op-exclude.txt
  php.ini
Labels: 2.2.1

#506 MCLOUD-2649: [opcache] Disable timestamps validation
  op-exclude.txt
  php.ini
Labels: 2.2.2

#505 MCLOUD-2649: [opcache] Disable timestamps validation
  op-exclude.txt
  php.ini
Labels: 2.2.3

#504 MCLOUD-2649: [opcache] Disable timestamps validation
  op-exclude.txt
  php.ini
Labels: 2.2.4

#503 MCLOUD-2649: [opcache] Disable timestamps validation
  op-exclude.txt
  php.ini
Labels: 2.2.5

#486 MCLOUD-2649: [opcache] Disable timestamps validation
  op-exclude.txt
  php.ini
Labels: 2.1.4

#487 MCLOUD-2649: [opcache] Disable timestamps validation
  op-exclude.txt
  php.ini
Labels: 2.1.16

#488 MCLOUD-2649: [opcache] Disable timestamps validation
  op-exclude.txt
  php.ini
Labels: 2.1.17

#491 MCLOUD-2649: [opcache] Disable timestamps validation
  op-exclude.txt
  php.ini
Labels: 2.3.5

#492 MCLOUD-2649: [opcache] Disable timestamps validation
  op-exclude.txt
  php.ini
Labels: 2.3.4

#493 MCLOUD-2649: [opcache] Disable timestamps validation
  op-exclude.txt
  php.ini
Labels: 2.3.3

#494 MCLOUD-2649: [opcache] Disable timestamps validation
  op-exclude.txt
  php.ini
Labels: 2.3.2

#495 MCLOUD-2649: [opcache] Disable timestamps validation
  op-exclude.txt
  php.ini
Labels: 2.3.1

#496 MCLOUD-2649: [opcache] Disable timestamps validation
  op-exclude.txt
  php.ini
Labels: 2.3.0

#497 MCLOUD-2649: [opcache] Disable timestamps validation
  op-exclude.txt
  php.ini
Labels: 2.2.11

#498 MCLOUD-2649: [opcache] Disable timestamps validation
  op-exclude.txt
  php.ini
Labels: 2.2.10

#499 MCLOUD-2649: [opcache] Disable timestamps validation
  op-exclude.txt
  php.ini
Labels: 2.2.9

#500 MCLOUD-2649: [opcache] Disable timestamps validation
  op-exclude.txt
  php.ini
Labels: 2.2.8

#501 MCLOUD-2649: [opcache] Disable timestamps validation
  op-exclude.txt
  php.ini
Labels: 2.2.7

#502 MCLOUD-2649: [opcache] Disable timestamps validation
  op-exclude.txt
  php.ini
Labels: 2.2.6
