Repository magento/magento-cloud, pull requests merged in 2020-02, with the labels that each got.

#443 MAGECLOUD-4080: Update default example in magento-vars.php
  magento-vars.php
Labels: 2.1.18

#442 MAGECLOUD-4080: Update default example in magento-vars.php
  magento-vars.php
Labels: 2.1.17

#441 MAGECLOUD-4080: Update default example in magento-vars.php
  magento-vars.php
Labels: 2.1.16

#412 MAGECLOUD-4080: Update default example in magento-vars.php
  magento-vars.php
Labels: 2.3.3

#413 MAGECLOUD-4080: Update default example in magento-vars.php
  magento-vars.php
Labels: 2.3.4

#414 MAGECLOUD-4080: Update default example in magento-vars.php
  magento-vars.php
Labels: 2.3.0

#415 MAGECLOUD-4080: Update default example in magento-vars.php
  magento-vars.php
Labels: 2.3.1

#416 MAGECLOUD-4080: Update default example in magento-vars.php
  magento-vars.php
Labels: 2.3.2

#417 MAGECLOUD-4080: Update default example in magento-vars.php
  magento-vars.php
Labels: 2.2.11

#418 MAGECLOUD-4080: Update default example in magento-vars.php
  magento-vars.php
Labels: 2.2.0

#419 MAGECLOUD-4080: Update default example in magento-vars.php
  magento-vars.php
Labels: 2.2.1

#420 MAGECLOUD-4080: Update default example in magento-vars.php
  magento-vars.php
Labels: 2.2.2

#421 MAGECLOUD-4080: Update default example in magento-vars.php
  magento-vars.php
Labels: 2.2.3

#422 MAGECLOUD-4080: Update default example in magento-vars.php
  magento-vars.php
Labels: 2.2.4

#423 MAGECLOUD-4080: Update default example in magento-vars.php
  magento-vars.php
Labels: 2.2.5

#424 MAGECLOUD-4080: Update default example in magento-vars.php
  magento-vars.php
Labels: 2.2.6

#425 MAGECLOUD-4080: Update default example in magento-vars.php
  magento-vars.php
Labels: 2.2.8

#426 MAGECLOUD-4080: Update default example in magento-vars.php
  magento-vars.php
Labels: 2.2.9

#427 MAGECLOUD-4080: Update default example in magento-vars.php
  magento-vars.php
Labels: 2.2.10

#428 MAGECLOUD-4080: Update default example in magento-vars.php
  magento-vars.php
Labels: 2.2.7

#411 MAGECLOUD-4080: Update default example in magento-vars.php
  magento-vars.php
Labels: approved, master

#445 Updating magento-cloud Template Licenses
  COPYING.txt
  LICENSE.txt
  README.md
  composer.json
Labels: approved, master
